# create atest file and write data inside it
# f=open("data.txt","w")
# f.write("ram is a good boy\n")
# f.write("hi bye\n")
# f.write("ok\n")
# f.close()
# f=open("data.txt","r")
# print(f.read(6))
# f.close()


# f=open("data.txt","r")
# print(f.readline())
# f.close()

# f=open("data.txt","r")
# print(f.readlines())
# f.close()

# f=open("data.txt","r")
# l=f.readlines()
# for i in l:
# 	print(i,end="")
# f.close()
# f1=open("data.txt","r")
# f2=open("data2.txt","w")
# f2.write(f1.read())
# f1.close()
# f2.close( )
# f=open("data.txt","w")
# f.write("a b cd e f g h i j k l m n o p q r s t u v wx y z")
# f=open("data.txt","r")
# f.seek(10)
# print(f.read())
# f.seek(0)
# print(f.read(3))
# print(f.tell())
# f.close()
# f=open("sita.txt","w")
# f.write("ram is a good boy")
# f.close()
# f=open("sita.txt","r")
# f.read()
# f.close()
# f=open("sita.txt","w+")
# f.write("sita is a good girl")
# f.seek(0)
# print(f.read())
# f.close()
# f=open("sita.txt","a+")
# f.write("sita is a good girl")
# f.seek(0)
# print(f.read())
# f.close()
# f=open("sita.txt","r+")
# print(f.read())
# f.write("ok")
# f.close()
# write a list in a file using text file conept typecasting must be nessary
# f=open("sita.txt","w+")
# f.write(str([1,2,3]))
# f.close()
# f=open("sita.txt","r+")
# f.write(f.read( ))
# f.close()

# import pickle
# numbers=[10,20,30,40,50]
# f=open("xyz.data","wb")
# pickle.dump(numbers,f)
# f.close()

import pickle

f=open("xyz.data","rb")
l=pickle.load(f)
f.close()